# Generated by Django 4.2 on 2023-04-07 16:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('garden', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Calendar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frost_dates', models.DateField(blank=True, null=True)),
                ('plant_dates', models.DateField(blank=True, null=True)),
                ('harvest_times', models.DateTimeField(blank=True, null=True)),
                ('fertilize_dates', models.DateField(blank=True, null=True)),
                ('comments', models.TextField(blank=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='calenders', to='garden.user')),
            ],
        ),
    ]
