# Generated by Django 4.2 on 2023-04-07 16:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('garden', '0003_plant'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlantListing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('row_spacing', models.CharField(max_length=100)),
                ('seed_depth', models.CharField(blank=True, max_length=100, null=True)),
                ('sunlight_needs', models.CharField(blank=True, max_length=200, null=True)),
                ('season', models.CharField(blank=True, max_length=200, null=True)),
                ('water_needs', models.TextField(blank=True)),
                ('frost_tolerance', models.TextField(blank=True)),
                ('germination_time', models.CharField(blank=True, max_length=100, null=True)),
                ('harvest_times', models.CharField(blank=True, max_length=100, null=True)),
                ('grow_from_seed', models.BooleanField(blank=True, null=True)),
                ('grow_from_transplant', models.BooleanField(blank=True, null=True)),
                ('plant_needs_fertilization', models.BooleanField(blank=True, null=True)),
                ('date_to_plant', models.TextField(blank=True)),
                ('plant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plant_listings', to='garden.plant')),
            ],
        ),
    ]
